#!/usr/bin/env python3
"""Build indian_pop_culture_pairs.json — popular Indian pop-culture similar pairs."""

from __future__ import annotations

import json
from pathlib import Path

# Household names only. Pairs share category, era, or cultural vibe — not random zip.
SIMILAR_PAIRS: list[tuple[str, str]] = [
    # Bollywood actors
    ("Shah Rukh Khan", "Salman Khan"),
    ("Aamir Khan", "Hrithik Roshan"),
    ("Ranbir Kapoor", "Ranveer Singh"),
    ("Amitabh Bachchan", "Dharmendra"),
    ("Akshay Kumar", "Ajay Devgn"),
    ("Varun Dhawan", "Sidharth Malhotra"),
    ("Tiger Shroff", "Kartik Aaryan"),
    ("Shahid Kapoor", "Ayushmann Khurrana"),
    ("Rajinikanth", "Kamal Haasan"),
    ("Prabhas", "Allu Arjun"),
    ("Vijay", "Ajith"),
    ("NTR Jr", "Ram Charan"),
    ("Yash", "Dhanush"),
    ("Mahesh Babu", "Pawan Kalyan"),
    ("Anil Kapoor", "Jackie Shroff"),
    ("Sanjay Dutt", "Suniel Shetty"),
    ("Govinda", "David Dhawan"),
    ("Emraan Hashmi", "Imran Khan"),
    ("John Abraham", "Abhishek Bachchan"),
    ("Saif Ali Khan", "Farhan Akhtar"),
    # Bollywood actresses
    ("Deepika Padukone", "Priyanka Chopra"),
    ("Alia Bhatt", "Katrina Kaif"),
    ("Kareena Kapoor", "Karisma Kapoor"),
    ("Madhuri Dixit", "Sridevi"),
    ("Kajol", "Rani Mukerji"),
    ("Anushka Sharma", "Sonam Kapoor"),
    ("Kangana Ranaut", "Vidya Balan"),
    ("Shraddha Kapoor", "Kiara Advani"),
    ("Janhvi Kapoor", "Sara Ali Khan"),
    ("Nayanthara", "Trisha"),
    ("Samantha", "Rashmika Mandanna"),
    ("Alia Bhatt", "Deepika Padukone"),
    ("Priyanka Chopra", "Anushka Sharma"),
    ("Kriti Sanon", "Disha Patani"),
    ("Taapsee Pannu", "Bhumi Pednekar"),
    # Food & street food
    ("Biryani", "Pulao"),
    ("Dosa", "Idli"),
    ("Samosa", "Pakora"),
    ("Chai", "Filter Coffee"),
    ("Butter Chicken", "Chicken Tikka"),
    ("Naan", "Roti"),
    ("Paneer", "Tofu"),
    ("Pani Puri", "Bhel Puri"),
    ("Vada Pav", "Pav Bhaji"),
    ("Masala Dosa", "Rava Dosa"),
    ("Rajma", "Chole"),
    ("Dal Makhani", "Dal Tadka"),
    ("Lassi", "Chaas"),
    ("Gulab Jamun", "Rasgulla"),
    ("Jalebi", "Imarti"),
    ("Kheer", "Payasam"),
    ("Barfi", "Ladoo"),
    ("Poha", "Upma"),
    ("Tandoori", "Kebab"),
    ("Momos", "Dim Sum"),
    ("Hakka Noodles", "Chow Mein"),
    ("Dahi Puri", "Sev Puri"),
    ("Frankie", "Shawarma"),
    ("Maggi", "Instant Noodles"),
    ("Chole Bhature", "Amritsari Kulcha"),
    ("Misal Pav", "Vada Pav"),
    ("Kulfi", "Ice Cream"),
    ("Falooda", "Milkshake"),
    ("Thandai", "Lassi"),
    ("Aloo Paratha", "Gobi Paratha"),
    ("Puri Bhaji", "Halwa Puri"),
    ("Dhokla", "Khandvi"),
    ("Thepla", "Paratha"),
    ("Chicken 65", "Gobi 65"),
    ("Pav Bhaji", "Misal Pav"),
    ("Cutting Chai", "Irani Chai"),
    ("Masala Chai", "Adrak Chai"),
    ("Bhelpuri", "Sev Puri"),
    ("Rasmalai", "Sandesh"),
    # Cricket
    ("IPL", "T20 World Cup"),
    ("Mumbai Indians", "Chennai Super Kings"),
    ("Royal Challengers Bangalore", "Kolkata Knight Riders"),
    ("Virat Kohli", "Rohit Sharma"),
    ("MS Dhoni", "Yuvraj Singh"),
    ("Sachin Tendulkar", "Rahul Dravid"),
    ("Hardik Pandya", "Ravindra Jadeja"),
    ("Wankhede Stadium", "Eden Gardens"),
    ("World Cup", "Champions Trophy"),
    ("Asia Cup", "IPL Final"),
    ("Gully Cricket", "Box Cricket"),
    ("Sunrisers Hyderabad", "Delhi Capitals"),
    ("Punjab Kings", "Rajasthan Royals"),
    ("Gujarat Titans", "Lucknow Super Giants"),
    ("Rishabh Pant", "KL Rahul"),
    ("Jasprit Bumrah", "Mohammed Shami"),
    ("Ravichandran Ashwin", "Ravindra Jadeja"),
    ("Chepauk Stadium", "Chinnaswamy Stadium"),
    ("Harsha Bhogle", "Ravi Shastri"),
    ("IPL Auction", "IPL Opening Ceremony"),
    ("Cricket Commentary", "Match Highlights"),
    # Festivals & weddings
    ("Diwali", "Holi"),
    ("Eid", "Bakrid"),
    ("Navratri", "Durga Puja"),
    ("Ganesh Chaturthi", "Janmashtami"),
    ("Pongal", "Onam"),
    ("Baisakhi", "Lohri"),
    ("Raksha Bandhan", "Karva Chauth"),
    ("Sangeet", "Mehendi"),
    ("Haldi", "Mehendi Ceremony"),
    ("Barat", "Reception"),
    ("Saree", "Lehenga"),
    ("Sherwani", "Kurta"),
    ("Rangoli", "Kolam"),
    ("Diya", "Lantern"),
    ("Fireworks", "Sparklers"),
    ("Puja", "Aarti"),
    ("Garba", "Dandiya"),
    ("Bhang", "Thandai"),
    ("Kite Flying", "Patang"),
    ("Wedding Mandap", "Reception Stage"),
    ("Bindi", "Sindoor"),
    ("Mehendi", "Henna"),
    ("Temple Visit", "Gurudwara Visit"),
    ("Christmas", "New Year Party"),
    ("Diwali Lights", "Fairy Lights"),
    # TV, OTT & reality
    ("Kaun Banega Crorepati", "Bigg Boss"),
    ("The Kapil Sharma Show", "Comedy Nights"),
    ("Taarak Mehta Ka Ooltah Chashmah", "Bhabhi Ji Ghar Par Hai"),
    ("CID", "Crime Patrol"),
    ("Ramayan", "Mahabharat"),
    ("Sa Re Ga Ma Pa", "Indian Idol"),
    ("Dance India Dance", "Boogie Woogie"),
    ("Roadies", "Splitsvilla"),
    ("Shark Tank India", "Dragon's Den"),
    ("Jhalak Dikhla Jaa", "Nach Baliye"),
    ("The Family Man", "Mirzapur"),
    ("Sacred Games", "Scam 1992"),
    ("Panchayat", "Gullak"),
    ("Kota Factory", "Aspirants"),
    ("Hotstar", "Netflix"),
    ("SonyLIV", "Prime Video"),
    ("Zee5", "JioCinema"),
    ("Colors TV", "Star Plus"),
    ("SAB TV", "Sony TV"),
    ("MTV India", "Vh1 India"),
    # Music
    ("Arijit Singh", "Atif Aslam"),
    ("Sonu Nigam", "Shaan"),
    ("Sunidhi Chauhan", "Shreya Ghoshal"),
    ("Badshah", "Yo Yo Honey Singh"),
    ("AR Rahman", "Pritam"),
    ("Lata Mangeshkar", "Asha Bhosle"),
    ("Kishore Kumar", "Mohammed Rafi"),
    ("Neha Kakkar", "Tulsi Kumar"),
    ("Sidhu Moose Wala", "AP Dhillon"),
    ("Diljit Dosanjh", "Guru Randhawa"),
    ("Coke Studio", "MTV Unplugged"),
    ("Gaana", "JioSaavn"),
    ("Spotify", "Apple Music"),
    ("Bhangra", "Punjabi Pop"),
    ("Qawwali", "Sufi Music"),
    ("Antakshari", "Karaoke"),
    ("Item Song", "Dance Number"),
    ("Ilaiyaraaja", "SP Balasubrahmanyam"),
    ("Arijit Singh", "Jubin Nautiyal"),
    ("Ritviz", "Prateek Kuhad"),
    ("Divine", "Raftaar"),
    ("KK", "Sonu Nigam"),
    ("Shreya Ghoshal", "Palak Muchhal"),
    ("Pritam", "Vishal-Shekhar"),
    # Apps & brands
    ("Zomato", "Swiggy"),
    ("Paytm", "PhonePe"),
    ("Google Pay", "BHIM UPI"),
    ("Flipkart", "Amazon India"),
    ("Ola", "Uber"),
    ("IRCTC", "MakeMyTrip"),
    ("BookMyShow", "Paytm Insider"),
    ("CRED", "BharatPe"),
    ("Blinkit", "Zepto"),
    ("BigBasket", "Grofers"),
    ("Nykaa", "Myntra"),
    ("Jio", "Airtel"),
    ("Dunzo", "Swiggy Instamart"),
    ("Meesho", "Ajio"),
    ("BYJU'S", "Unacademy"),
    ("OYO", "Treebo"),
    ("Rapido", "Uber Moto"),
    ("ShareChat", "Josh"),
    ("Dream11", "MPL"),
    ("Policybazaar", "Paytm Insurance"),
    # Cities & landmarks
    ("Mumbai", "Delhi"),
    ("Bangalore", "Hyderabad"),
    ("Chennai", "Kochi"),
    ("Pune", "Ahmedabad"),
    ("Jaipur", "Udaipur"),
    ("Goa", "Pondicherry"),
    ("Shimla", "Manali"),
    ("Darjeeling", "Ooty"),
    ("Varanasi", "Haridwar"),
    ("Chandigarh", "Ludhiana"),
    ("Marine Drive", "Gateway of India"),
    ("India Gate", "Qutub Minar"),
    ("Taj Mahal", "Red Fort"),
    ("Local Train", "Metro"),
    ("Auto Rickshaw", "Cab"),
    ("Dhaba", "Restaurant"),
    ("Kirana Store", "Supermarket"),
    ("Sabzi Mandi", "Fish Market"),
    ("Hill Station", "Beach Town"),
    ("Old Delhi", "Chandni Chowk"),
    # Brands & everyday India
    ("Haldiram's", "Bikanervala"),
    ("Amul Butter", "Britannia Butter"),
    ("Parle-G", "Monaco Biscuits"),
    ("Frooti", "Maaza"),
    ("Thums Up", "Coca-Cola"),
    ("Old Monk", "Royal Stag"),
    ("Rajma Chawal", "Dal Chawal"),
    ("Hyderabadi Biryani", "Lucknowi Biryani"),
    ("Paneer Tikka", "Chicken Tikka"),
    ("Palak Paneer", "Saag Paneer"),
    ("Chicken Biryani", "Mutton Biryani"),
    ("Masala Papad", "Roasted Papad"),
    ("Aloo Gobi", "Mix Veg"),
    ("Fish Fry", "Pomfret Fry"),
    ("Butter Naan", "Garlic Naan"),
    ("Rogan Josh", "Vindaloo"),
    ("Pickle", "Chutney"),
    ("Raita", "Curd"),
    ("Tandoori Chicken", "Butter Chicken"),
    # Regional culture
    ("Punjabi", "Hindi"),
    ("Tamil", "Telugu"),
    ("Bengali", "Marathi"),
    ("Gujarati", "Rajasthani"),
    ("South Indian", "North Indian"),
    ("Dhaba Food", "Home Food"),
    ("Tiffin", "Lunch Box"),
    ("Coaching Class", "Tuition"),
    ("Board Exam", "Entrance Exam"),
    ("Arranged Marriage", "Love Marriage"),
    ("Joint Family", "Nuclear Family"),
    ("NRI", "Desi Abroad"),
    ("Kollywood", "Sandalwood"),
    ("Punjabi Wedding", "Sikh Wedding"),
    ("Filter Coffee", "Masala Chai"),
    ("Rickshaw", "Cab Ride"),
    ("Bollywood Dance", "Bhangra"),
    ("Engineering College", "Medical College"),
    ("Campus Placement", "Internship"),
    ("Rent Agreement", "Broker"),
    ("Society Watchman", "Building Security"),
    ("Power Cut", "Inverter Backup"),
    ("Water Tanker", "Borewell"),
    ("First Show", "Matinee"),
    ("Corner Seat", "Balcony Seat"),
    ("Interval", "Intermission"),
    ("Single Screen", "Multiplex"),
    ("First Day First Show", "Premiere"),
    ("Fan Club", "Fan Page"),
    ("Paisa Vasool", "Blockbuster Hit"),
    # Snacks, sweets & drinks
    ("Samosa", "Kachori"),
    ("Kachori", "Bedmi Puri"),
    ("Aloo Tikki", "Chaat"),
    ("Papdi Chaat", "Dahi Bhalla"),
    ("Rasmalai", "Rabri"),
    ("Modak", "Ladoo"),
    ("Pedha", "Barfi"),
    ("Soan Papdi", "Patisa"),
    ("Masala Soda", "Nimbu Pani"),
    ("Nimbu Pani", "Shikanji"),
    ("Cold Coffee", "Frappe"),
    ("Masala Chai", "Ginger Tea"),
    ("Filter Kaapi", "Degree Coffee"),
    ("Panipuri", "Golgappa"),
    ("Bhel", "Jhalmuri"),
    ("Bhatura", "Poori"),
    ("Paratha", "Naan"),
    ("Tandoori Roti", "Roomali Roti"),
    ("Paneer Butter Masala", "Shahi Paneer"),
    # Sports beyond cricket
    ("Kabaddi", "Kho Kho"),
    ("Hockey", "Football"),
    ("Badminton", "Table Tennis"),
    ("Chess", "Carrom"),
    ("PV Sindhu", "Saina Nehwal"),
    ("Neeraj Chopra", "Abhinav Bindra"),
    ("Leander Paes", "Mahesh Bhupathi"),
    ("Mumbai Marathon", "Delhi Half Marathon"),
    ("Gully Football", "Street Cricket"),
    ("Pro Kabaddi League", "Pro Wrestling League"),
    ("Hockey India League", "Indian Super League"),
    ("Sunil Chhetri", "Bhaichung Bhutia"),
    ("Mary Kom", "Vijender Singh"),
    # Social & internet culture
    ("Meme Page", "Reels Account"),
    ("Instagram Reels", "YouTube Shorts"),
    ("WhatsApp Group", "Telegram Channel"),
    ("Family Group", "Friends Group"),
    ("Good Morning Message", "Forward Message"),
    ("Status Update", "Story"),
    ("Influencer", "Content Creator"),
    ("Vlog", "Podcast"),
    ("Stand-Up Comedy", "Roast Show"),
    ("Open Mic", "Comedy Club"),
    ("Wedding Sangeet", "Sangeet Night"),
    ("Shaadi.com", "Bumble"),
    ("Arranged Match", "Swipe Right"),
    ("Big Fat Wedding", "Destination Wedding"),
    ("Mehendi Night", "Haldi Function"),
    # Classic pop references
    ("DDLJ", "Mohabbatein"),
    ("Sholay", "Deewar"),
    ("Lagaan", "Chak De India"),
    ("3 Idiots", "PK"),
    ("Dangal", "Sultan"),
    ("KBC Host", "Bigg Boss Host"),
    ("Rajesh Khanna", "Dev Anand"),
    ("Helen", "Zeenat Aman"),
    ("Rishi Kapoor", "Jeetendra"),
    ("Rekha", "Hema Malini"),
    ("Amitabh Voice", "Pran Voice"),
    ("Filmy Dialogue", "One-Liner"),
    ("Masala Film", "Family Entertainer"),
    ("Item Number", "Romantic Song"),
    ("Background Score", "Title Track"),
    ("Pathaan", "Jawan"),
    ("Gully Boy", "Rockstar"),
    ("Chennai Express", "Dilwale"),
    ("Kapil Sharma", "Krushna Abhishek"),
    ("Manish Malhotra", "Sabyasachi"),
    ("Suhana Khan", "Khushi Kapoor"),
    ("Ranveer Singh", "Ranbir Kapoor"),
    ("Koffee with Karan", "The Kapil Sharma Show"),
    ("Filmfare Awards", "IIFA Awards"),
    ("Red Fort", "India Gate Rally"),
    ("Marine Lines", "Bandra-Worli Sea Link"),
    ("Local Train", "Virar Fast"),
    ("Dabbawala", "Swiggy Delivery"),
    ("Auto Stand", "Cab Booking"),
    # Batch 2 — expand to 500 pairs
    # Bollywood films
    ("Baahubali", "RRR"),
    ("KGF", "Pushpa"),
    ("Stree", "Bala"),
    ("Andhadhun", "Badla"),
    ("Queen", "English Vinglish"),
    ("Drishyam", "Drishyam 2"),
    ("War", "Tiger"),
    ("Brahmastra", "Adipurush"),
    ("Stree 2", "Munjya"),
    ("Animal", "Kabir Singh"),
    ("Dream Girl", "Bala"),
    ("Badhaai Do", "Shubh Mangal Saavdhan"),
    ("Tumbbad", "Stree"),
    ("Haider", "Omkara"),
    ("Omkara", "Maqbool"),
    ("Zindagi Na Milegi Dobara", "Dil Chahta Hai"),
    ("Kal Ho Naa Ho", "Kuch Kuch Hota Hai"),
    ("Kuch Kuch Hota Hai", "Kabhi Khushi Kabhie Gham"),
    ("Hum Aapke Hain Kaun", "Hum Saath Saath Hain"),
    ("Main Hoon Na", "Om Shanti Om"),
    ("Om Shanti Om", "Happy New Year"),
    ("Golmaal", "Housefull"),
    ("Golmaal Returns", "Housefull 2"),
    ("Dhoom", "Dhoom 2"),
    ("Bang Bang", "War"),
    ("Race", "Race 2"),
    ("Wanted", "Dabangg"),
    ("Dabangg", "Rowdy Rathore"),
    ("Singham", "Simmba"),
    ("Simmba", "Sooryavanshi"),
    ("Student of the Year", "Student of the Year 2"),
    ("Ae Dil Hai Mushkil", "Kabhi Alvida Naa Kehna"),
    ("Barfi", "Piku"),
    ("Piku", "Pink"),
    ("Pink", "Chhapaak"),
    ("Taare Zameen Par", "Stanley Ka Dabba"),
    ("Munna Bhai MBBS", "Lage Raho Munna Bhai"),
    ("Hera Pheri", "Phir Hera Pheri"),
    ("Welcome", "Hungama"),
    ("Bhool Bhulaiyaa", "Stree"),
    ("Toilet Ek Prem Katha", "Pad Man"),
    ("Pad Man", "Mission Mangal"),
    ("Mission Mangal", "Shakuntala Devi"),
    ("Uri", "Kesari"),
    ("Kesari", "Tanhaji"),
    ("Tanhaji", "Panipat"),
    ("Raazi", "Ghazi Attack"),
    ("Raees", "Ra.One"),
    ("Ra.One", "Fan"),
    ("Bhediya", "Bhoot Police"),
    ("Pushpa 2", "Pushpa"),
    ("Kalki 2898 AD", "Brahmastra"),
    ("Gangubai Kathiawadi", "Thalaivi"),
    ("Heeramandi", "Maharani"),
    # Directors & filmmakers
    ("Karan Johar", "Farah Khan"),
    ("Sanjay Leela Bhansali", "Ashutosh Gowariker"),
    ("Anurag Kashyap", "Imtiaz Ali"),
    ("Zoya Akhtar", "Reema Kagti"),
    ("Rajkumar Hirani", "Shoojit Sircar"),
    ("Vishal Bhardwaj", "Anurag Kashyap"),
    ("Rohit Shetty", "Atlee"),
    ("Atlee", "Shankar"),
    ("Shankar", "Mani Ratnam"),
    ("Mani Ratnam", "Sanjay Leela Bhansali"),
    # More actors
    ("Nawazuddin Siddiqui", "Manoj Bajpayee"),
    ("Irrfan Khan", "Nawazuddin Siddiqui"),
    ("Pankaj Tripathi", "Manoj Bajpayee"),
    ("Rajkummar Rao", "Vicky Kaushal"),
    ("Sushant Singh Rajput", "Vicky Kaushal"),
    ("Jacqueline Fernandez", "Nora Fatehi"),
    ("Mouni Roy", "Hina Khan"),
    ("Urvashi Rautela", "Sunny Leone"),
    ("Juhi Chawla", "Tabu"),
    ("Tabu", "Konkona Sen Sharma"),
    ("Ratna Pathak", "Supriya Pathak"),
    ("Paresh Rawal", "Om Puri"),
    ("Nana Patekar", "Anupam Kher"),
    ("Boman Irani", "Anupam Kher"),
    ("Johnny Lever", "Rajpal Yadav"),
    ("Sunil Grover", "Krishna Abhishek"),
    ("Bharti Singh", "Sumona Chakravarti"),
    ("Shehnaaz Gill", "Jasmin Bhasin"),
    ("Chunky Pandey", "Shakti Kapoor"),
    ("Shakti Kapoor", "Gulshan Grover"),
    ("Gulshan Grover", "Prem Chopra"),
    ("Amrish Puri", "Prem Chopra"),
    ("Prakash Raj", "Nassar"),
    ("Rana Daggubati", "Rakul Preet"),
    ("Tamannaah", "Shruti Haasan"),
    ("Keerthy Suresh", "Sai Pallavi"),
    ("Dulquer Salmaan", "Fahadh Faasil"),
    ("Mohanlal", "Mammootty"),
    ("Mammootty", "Prithviraj"),
    # TV & OTT
    ("Anupama", "Yeh Rishta Kya Kehlata Hai"),
    ("Yeh Rishta Kya Kehlata Hai", "Ghum Hai Kisikey Pyaar Meiin"),
    ("Naagin", "Sasural Simar Ka"),
    ("Kumkum Bhagya", "Kundali Bhagya"),
    ("Balika Vadhu", "Uttaran"),
    ("Comedy Nights with Kapil", "The Great Indian Laughter Challenge"),
    ("Indian Matchmaking", "Made in Heaven"),
    ("Made in Heaven", "Four More Shots Please"),
    ("Delhi Crime", "Paatal Lok"),
    ("Special Ops", "Asur"),
    ("Faadu", "Jubilee"),
    ("Aarya", "Criminal Justice"),
    ("Broken But Beautiful", "Never Kiss Your Best Friend"),
    ("Class", "Hostel Daze"),
    ("Hostel Daze", "College Romance"),
    ("Permanent Roommates", "Tripling"),
    ("Little Things", "Modern Love Mumbai"),
    ("Flames", "College Romance"),
    ("TVF Pitchers", "TVF Tripling"),
    ("Rocket Boys", "Maharani"),
    ("Jubilee", "Sultan of Delhi"),
    # Music
    ("Shekhar Ravjiani", "Vishal Dadlani"),
    ("Shankar Mahadevan", "Hariharan"),
    ("Udit Narayan", "Kumar Sanu"),
    ("Kumar Sanu", "Abhijeet"),
    ("Alka Yagnik", "Kavita Krishnamurthy"),
    ("Kavita Krishnamurthy", "Sadhana Sargam"),
    ("Benny Dayal", "Armaan Malik"),
    ("Armaan Malik", "Darshan Raval"),
    ("MC Stan", "Ikka"),
    ("Sachin-Jigar", "Amit Trivedi"),
    ("Amit Trivedi", "Salim-Sulaiman"),
    ("Salim-Sulaiman", "Shankar-Ehsaan-Loy"),
    ("Ismail Darbar", "Anu Malik"),
    ("Anu Malik", "Himesh Reshammiya"),
    ("Himesh Reshammiya", "Mika Singh"),
    # Regional food
    ("Appam", "Puttu"),
    ("Mysore Pak", "Halwa"),
    ("Mysore Bonda", "Medu Vada"),
    ("Medu Vada", "Sambar Vada"),
    ("Sambar", "Rasam"),
    ("Rasam", "Pulusu"),
    ("Chettinad Chicken", "Andhra Chicken"),
    ("Gongura", "Pachadi"),
    ("Avial", "Thoran"),
    ("Thoran", "Poriyal"),
    ("Pesarattu", "Neer Dosa"),
    ("Malabar Parotta", "Kerala Parotta"),
    ("Kerala Sadya", "Onam Sadya"),
    ("Galouti Kebab", "Seekh Kebab"),
    ("Seekh Kebab", "Shami Kebab"),
    ("Shami Kebab", "Reshmi Kebab"),
    ("Reshmi Kebab", "Tangdi Kebab"),
    ("Litti Chokha", "Baati Chokha"),
    ("Baati Chokha", "Dal Baati"),
    ("Chana Masala", "Chole Masala"),
    ("Malai Kofta", "Navratan Korma"),
    ("Navratan Korma", "Malai Matar"),
    ("Malai Matar", "Matar Paneer"),
    ("Kadi Pakoda", "Kadi Chawal"),
    ("Kadi Chawal", "Khichdi"),
    ("Bisibele Bath", "Puliyogare"),
    ("Puliyogare", "Lemon Rice"),
    ("Lemon Rice", "Curd Rice"),
    ("Curd Rice", "Tamarind Rice"),
    ("Sabudana Khichdi", "Sabudana Vada"),
    ("Misal", "Usal"),
    ("Zunka Bhakar", "Pitla Bhakri"),
    ("Khandvi", "Muthia"),
    ("Muthia", "Handvo"),
    ("Handvo", "Dal Dhokli"),
    ("Dal Dhokli", "Undhiyu"),
    ("Kashmiri Wazwan", "Kahwa"),
    ("Kahwa", "Noon Chai"),
    ("Bun Maska", "Brun Maska"),
    ("Brun Maska", "Maska Pav"),
    ("Kolkata Biryani", "Awadhi Biryani"),
    # Cricket personalities
    ("Gautam Gambhir", "Virender Sehwag"),
    ("Sourav Ganguly", "Anil Kumble"),
    ("Anil Kumble", "Harbhajan Singh"),
    ("Zaheer Khan", "Irfan Pathan"),
    ("Irfan Pathan", "Munaf Patel"),
    ("Suresh Raina", "Dinesh Karthik"),
    ("Dinesh Karthik", "Wriddhiman Saha"),
    ("Shikhar Dhawan", "Gautam Gambhir"),
    ("Axar Patel", "Washington Sundar"),
    ("Washington Sundar", "Shardul Thakur"),
    ("Shardul Thakur", "Deepak Chahar"),
    ("Deepak Chahar", "Bhuvneshwar Kumar"),
    ("Kuldeep Yadav", "Yuzvendra Chahal"),
    ("Ishan Kishan", "Sanju Samson"),
    ("Mohammed Siraj", "Arshdeep Singh"),
    ("Arshdeep Singh", "Umran Malik"),
    ("Umran Malik", "Navdeep Saini"),
    # Cities & landmarks
    ("Kolkata", "Howrah"),
    ("Howrah Bridge", "Vidyasagar Setu"),
    ("Victoria Memorial", "Indian Museum"),
    ("Juhu Beach", "Versova Beach"),
    ("Versova Beach", "Aksa Beach"),
    ("Bandra Fort", "Carter Road"),
    ("Carter Road", "Bandstand"),
    ("Colaba Causeway", "Linking Road"),
    ("Linking Road", "Hill Road"),
    ("Connaught Place", "Khan Market"),
    ("Khan Market", "Sarojini Nagar"),
    ("Sarojini Nagar", "Lajpat Nagar"),
    ("Hauz Khas", "GK M Block"),
    ("Cyber Hub", "DLF Phase 3"),
    ("MG Road", "Brigade Road"),
    ("Brigade Road", "Commercial Street"),
    ("Cubbon Park", "Lalbagh"),
    ("Lalbagh", "Nandi Hills"),
    ("Charminar", "Hussain Sagar"),
    ("Hussain Sagar", "Necklace Road"),
    ("Haji Ali", "Siddhivinayak"),
    ("Siddhivinayak", "Mahalaxmi Temple"),
    ("Golden Temple", "Akshardham"),
    ("Akshardham", "Lotus Temple"),
    ("Lotus Temple", "Iskcon Temple"),
    ("Rishikesh", "Roorkee"),
    ("Mussoorie", "Nainital"),
    ("Nainital", "Ranikhet"),
    ("Kasol", "Dharamshala"),
    ("Dharamshala", "McLeod Ganj"),
    ("McLeod Ganj", "Dalhousie"),
    ("Dalhousie", "Spiti Valley"),
    ("Spiti Valley", "Ladakh"),
    ("Ladakh", "Leh"),
    ("Leh", "Kargil"),
    ("Andaman", "Lakshadweep"),
    ("Alleppey", "Munnar"),
    ("Munnar", "Wayanad"),
    ("Wayanad", "Coorg"),
    ("Coorg", "Chikmagalur"),
    ("Hampi", "Badami"),
    ("Badami", "Bijapur"),
    ("Jaisalmer", "Jodhpur"),
    ("Jodhpur", "Bikaner"),
    ("Bikaner", "Pushkar"),
    ("Pushkar", "Ajmer"),
    ("Mount Abu", "Pushkar"),
    # Brands & apps
    ("Mamaearth", "Wow Skin Science"),
    ("Boat", "Noise"),
    ("Lenskart", "Titan Eye Plus"),
    ("Urban Company", "Housejoy"),
    ("Practo", "1mg"),
    ("1mg", "PharmEasy"),
    ("PharmEasy", "Netmeds"),
    ("Dominos", "Pizza Hut"),
    ("Pizza Hut", "Papa Johns"),
    ("KFC", "Burger King"),
    ("Burger King", "McDonalds India"),
    ("McDonalds India", "Taco Bell India"),
    ("Cafe Coffee Day", "Starbucks India"),
    ("Starbucks India", "Barista"),
    ("Barista", "Theobroma"),
    ("Theobroma", "Oven Story"),
    ("Licious", "Freshtohome"),
    ("Country Delight", "Milkbasket"),
    ("Milkbasket", "Supr Daily"),
    ("Rapido", "Namma Yatri"),
    ("Namma Yatri", "Ola Auto"),
    ("Goibibo", "Cleartrip"),
    ("Cleartrip", "EaseMyTrip"),
    ("EaseMyTrip", "Yatra"),
    ("Zerodha", "Groww"),
    ("Groww", "Upstox"),
    ("Upstox", "Angel One"),
    ("Amazon Pay", "Samsung Pay"),
    ("Classplus", "Physics Wallah"),
    ("Physics Wallah", "Allen Institute"),
    ("Allen Institute", "Resonance Kota"),
    ("Vedantu", "Extramarks"),
    ("WhiteHat Jr", "Cuemath"),
    ("Cuemath", "Khan Academy India"),
    # Everyday India
    ("PG Accommodation", "Flatmate Hunt"),
    ("Broker Commission", "Token Amount"),
    ("Society Meeting", "RWA Notice"),
    ("RWA Notice", "Maintenance Bill"),
    ("Maintenance Bill", "Electricity Bill"),
    ("Electricity Bill", "Water Bill"),
    ("Water Bill", "Gas Bill"),
    ("Gas Bill", "LPG Subsidy"),
    ("LPG Subsidy", "UPI Payment"),
    ("ATM Queue", "Bank Passbook"),
    ("Bank Passbook", "Fixed Deposit"),
    ("Fixed Deposit", "Mutual Fund SIP"),
    ("Mutual Fund SIP", "Stock Market"),
    ("Diwali Bonus", "Increment Letter"),
    ("Increment Letter", "Appraisal Season"),
    ("Appraisal Season", "Layoff News"),
    ("H1B Visa", "Canada PR"),
    ("Canada PR", "UK Student Visa"),
    ("UK Student Visa", "Australia PR"),
    ("NRI Return", "Reverse Migration"),
    ("Shaadi Biodata", "Matrimonial Ad"),
    ("Matrimonial Ad", "Pandit Ji"),
    ("Pandit Ji", "Matchmaker Aunty"),
    ("Matchmaker Aunty", "Rishta Profile"),
    ("Rishta Profile", "LinkedIn Profile"),
    ("LinkedIn Profile", "Naukri Profile"),
    ("Naukri Profile", "Internshala"),
    ("Internshala", "Campus Hiring"),
    ("Freshers Party", "Farewell Party"),
    ("Farewell Party", "Convocation Day"),
    ("Convocation Day", "Degree Certificate"),
    ("Degree Certificate", "Marksheet"),
    ("Marksheet", "Migration Certificate"),
    ("Migration Certificate", "Bonafide Letter"),
    ("Bonafide Letter", "Fee Receipt"),
    ("Fee Receipt", "Donation Quota"),
    ("Donation Quota", "Management Seat"),
    ("Management Seat", "Rank List"),
    ("Rank List", "Counseling Round"),
    ("Counseling Round", "Seat Allotment"),
    ("Seat Allotment", "Hostel Room"),
]


def dedupe_similar_pairs(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    seen: set[str] = set()
    result: list[tuple[str, str]] = []
    for insider, mismatch in pairs:
        a = insider.casefold().strip()
        b = mismatch.casefold().strip()
        if not a or not b or a == b:
            continue
        if a in seen or b in seen:
            continue
        seen.add(a)
        seen.add(b)
        result.append((insider.strip(), mismatch.strip()))
    return result


def validate_pairs(pairs: list[tuple[str, str]], target: int = 500) -> None:
    if len(pairs) < target:
        raise ValueError(f"Need {target} pairs, got {len(pairs)}")

    seen_words: set[str] = set()
    for a, b in pairs[:target]:
        for word in (a, b):
            key = word.casefold().strip()
            if key in seen_words:
                raise ValueError(f"Repeated title: {word}")
            seen_words.add(key)


def build_pairs(target: int = 500) -> list[tuple[str, str]]:
    pairs = dedupe_similar_pairs(SIMILAR_PAIRS)
    if len(pairs) < target:
        raise ValueError(f"Need {target} similar pairs after dedupe, got {len(pairs)}")
    selected = pairs[:target]
    validate_pairs(selected, target)
    return selected


def main() -> None:
    pairs = build_pairs(500)
    out_dir = Path(__file__).resolve().parent
    payload = [{"insider": a, "mismatch": b} for a, b in pairs]
    out_path = out_dir / "indian_pop_culture_pairs.json"
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(pairs)} similar pairs to {out_path.name}")


if __name__ == "__main__":
    main()
